[[redirects]]
from = "/salary-calculator-2024-q1-mj-pavithra/*"
to = "index.html"
status = 200

[build]
command = "npm run build"
publish = "dist" 
  base = "."

[functions]
directory = "netlify/functions"

[deploy]
visibility = "public"
